### ISSUE TITLE
Please clarify the license of this project

### ISSUE THREAD

**Issue by ssb22** [danielt998/Wikidata-Dictionary-Generator#1]
The file cedict_ts.u8 says it's licensed under Creative Commons Attribution-Share Alike 3.0, but it is not clear what license the other files are under.  Please choose a license for the whole project so others will know what they may or may not do with it.

Wikidata itself is public-domain, but creating a derivative work of a public-domain work automatically gives you copyright on your edits (unless you explicitly give up these rights by saying your edits are also public domain), so you need to think about what license you'll put on it.

As you have a copy of CC-CEDICT in this repository, the license of the whole repository needs to be compatible with the license of CC-CEDICT.  If you want to be more permissive than CC-CEDICT (for example, if you want to drop the "Share-Alike" clause), then we'd need a clear separation of "parts influenced by CEDICT" from "parts not influenced by CEDICT" and that will be more difficult.  I suppose the easiest thing to do would be to simply add a Creative Commons Attribution-Share Alike 3.0 license file to the entire project (the Github web interface lets you do this in a few clicks) and postpone a consideration of being more permissive till later.

**Comment by danielt998** [comment]
Yeah that's a good shout, I'll add that for now, though I know it's discouraged to use creative Commons for software. Ideally I'd like it if the output could be public domain too if I could find another source for the pinyin data but that's a task for another day :)
